name: Nuclei scan

on:
  workflow_dispatch:



jobs:
  update-scope:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan with nuclei
        id: latest_scope
        run: |
          docker run --rm projectdiscovery/nuclei -u google.com -jsonl
